name: hundredminute_seller
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.5
  connectivity_plus: ^6.0.2
  dio: ^5.4.0
  shared_preferences: ^2.0.5
  shimmer: ^3.0.0
  flutter_switch: ^0.3.0
  fl_chart: ^0.67.0
  path_provider: ^2.0.0
  syncfusion_flutter_pdf: ^25.1.40
  flutter_local_notifications: ^17.0.1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  file_utils: ^1.0.1
  webview_flutter: ^4.0.2
  get: ^4.6.5
  cached_network_image: ^3.2.2

  open_file: ^3.2.1
  flutter_speed_dial: ^7.0.0
  flutter_filereader: ^3.0.0
  syncfusion_flutter_xlsio: ^25.1.40
  path: ^1.8.2
  excel: ^4.0.0
  image_picker: ^1.0.5
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.0.0+3
  file_picker: ^8.0.1
  syncfusion_flutter_charts: ^25.1.40
  intl: ^0.18.1

# dependency_overrides:
#   firebase_messaging_platform_interface: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/font/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/font/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/font/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/font/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 700
