name: hundredminute_seller
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  provider: ^5.0.0
  connectivity: ^3.0.3
  dio: ^4.0.0-prev2
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  flutter_switch: ^0.3.0
  fl_chart: ^0.55.2
  path_provider: ^2.0.11
  syncfusion_flutter_pdf: ^20.3.58
  flutter_local_notifications: ^12.0.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
#  dio: ^3.0.0
#  path_provider: ^1.3.0
#  simple_permissions: ^0.1.9
  file_utils: ^0.1.3
  webview_flutter: ^3.0.2
  get: ^4.6.5
  cached_network_image: ^3.2.2

  open_file: ^3.2.1
  flutter_speed_dial: ^6.2.0
  flutter_filereader: ^3.0.0
  syncfusion_flutter_xlsio: ^20.3.52-beta
  path: ^1.8.2
  excel: ^2.0.0-null-safety-3
  image_picker: ^0.8.6
  flutter_staggered_grid_view: ^0.6.2
  dotted_border: ^2.0.0+3
  file_picker: ^4.2.2


dependency_overrides:
  firebase_messaging_platform_interface: ^4.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/font/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/font/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/font/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/font/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 700