name: hundredminute_seller
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  provider: ^5.0.0
  connectivity: ^3.0.3
  dio: ^4.0.0-prev2
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0-nullsafety.0
  image_picker: ^0.7.4
  flutter_switch: ^0.3.0
  fl_chart: ^0.36.1
  path_provider: ^2.0.0
  syncfusion_flutter_pdf: ^19.4.50-beta
  flutter_local_notifications: ^5.0.0
  firebase_core: ^1.0.1
  flutter_staggered_grid_view: ^0.3.4
  dotted_border: ^2.0.0+2
  firebase_messaging: ^10.0.9
#  dio: ^3.0.0
#  path_provider: ^1.3.0
#  simple_permissions: ^0.1.9
  file_utils: ^0.1.3
  webview_flutter: ^3.0.2


dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/font/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/font/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/font/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/font/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 700